name: Release Steampipe Anywhere Components

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
        

jobs:
  anywhere_publish_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/steampipe-anywhere.yml@main
    secrets: inherit
